# Generated by Django 2.2.6 on 2019-12-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=12)),
                ('UserPassword', models.CharField(max_length=16)),
            ],
        ),
    ]
